# aws_ec2.yml
plugin: amazon.aws.aws_ec2
regions:
  - us-east-1

hostnames:
  - ip-address
  - tag:Name
  - dns-name

filters:
  tag:Name: hng-stage-4
  instance-state-name: running

compose:
  ansible_user: ubuntu
  ansible_ssh_private_key_file: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"

keyed_groups:
  - key: tags
    prefix: tag