plugin: amazon.aws.aws_ec2
aws_profile: default

regions:
  - "us-east-1"

strict: False

keyed_groups:
- key: tags
  prefix: tag

filters:
  tag:Name:
    - hng-stage-4
  instance-state-name : running
  
hostnames:
# a list in order of precedence for hostname variables.
  - tag:Name
  - dns-name
  - ip-address

compose:
  ansible_user: "ubuntu"  # Match your SSH user
  ansible_ssh_private_key_file: "~/.ssh/id_rsa"


 