- name: Install prerequisites
  apt:
    name:
      - ca-certificates
      - curl
    state: present
    update_cache: yes

- name: Create Docker GPG key directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

# - name: Add Docker's official GPG key
#   get_url:
#     url: https://download.docker.com/linux/ubuntu/gpg
#     dest: /etc/apt/keyrings/docker.asc
#     mode: '0644'
- name: Update CA certificates
  apt:
    name: ca-certificates
    state: latest

- name: Upgrade Python packages
  pip:
    name:
      - urllib3
      - pyOpenSSL
      - requests
    state: latest
    executable: pip3
    
- name: Add Docker's official GPG key (recommended method)
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_os_family == 'Debian'

- name: Add Docker repository
  apt_repository:
    repo: >-
      deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc]
      https://download.docker.com/linux/ubuntu
      {{ ansible_distribution_release }} stable
    filename: docker
    state: present

- name: Update package cache (after repo add)
  apt:
    update_cache: yes

- name: Install Docker components
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - docker-compose
    state: present

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Add current user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
